### ISSUE TITLE
package/search with a version 1 response should not return objects that don't have marathon

### ISSUE THREAD

**Issue by jsancio** [dcos/cosmos#425]
One solution is to create a v2 search request that takes a optional parameter. The optional parameter should indicate which packages type to return in the search. We need to investigate how to best express this filtering condition.

**Comment by cruhland** [comment]
Closing this issue after an offline discussion. Adding a filtering option to search requests was deemed too much of an ad-hoc solution without more information from Cosmos clients/users. The decision hinged on the following user outcomes:

1. _If this issue is implemented_: users of DC/OS 1.8 that request `v1` search responses will have CLI-only packages silently dropped from search results; the incomplete output would be inaccurate and could cause confusion, with nothing to inform the user that they should ask for `v2` responses instead.
1. _If this issue is **not** implemented_: users of DC/OS 1.8 will always see CLI-only packages; if they try to describe or install them when requesting `v1` responses, an explicit, specific error response will be sent. Users can then search for or ask for help on that error, which would hopefully result in them switching to `v2` responses.

In both cases, the scenario requires the use of an older CLI or web UI that does not ask for `v2` responses on a 1.8 DC/OS cluster. Since that is expected to be rare, it would be better to take option (2) above and see if customers actually run into trouble, before deciding to write code.

Please comment if I've forgotten to include or account for some information!
