### ISSUE TITLE
ContentType changes for Finch-0.11.0-m2

### ISSUE THREAD

**Issue by aeyakovenko** [dcos/cosmos#461]
ContentType changes for Finch-0.11.0-M2

* `withContentType` is deprecated
* need to change `Output` to `Response` via `_.toResponse[ContentType]`

```scala
  //from core/src/main/scala/io/finch/Output.scala
  implicit class OutputOps[A](val o: Output[A]) extends AnyVal {

    /**
     * Converts this [[Output]] to the HTTP response of the given `version`.
     */
    def toResponse[CT <: String](version: Version = Version.Http11)(implicit
      tr: ToResponse.Aux[A, CT],
      tre: ToResponse.Aux[Exception, CT]
    ): Response
  }
```
Content-type Types are explicit, subclass of String

MediaTypedEncoder will keep track of the content-type Type
```scala
  final class MediaTypedEncoder[A,CT <: String] private(val encoder: Encoder[A]) {
    type CT = CT
  }
```
`EndpointContext` can then use the `CT` type from the `responseEncoder` to convert to the appropriate finch response

```scala
Ok(encodedResponse).toResponse[context.responseEncoder.CT] 
```

generate explicit content-type Types, and convert to the MediaType instances from that type

```scala
Type UninstallRequest = Witness.`"application/vnd.dcos.cosmos.uninstall-request+json"`.T

toMediaType[CT<:String](ct :CT): MediaType = ct match {
  //hard-coded `kind` value for clarity, should be parsed from `ct`
  case UninstallRequest => MediaType.vnd(kind = "uninstall-request")
  case _ => sys.error(s“toMediaType unknown type ${ct.toString}”)
}
```

**Comment by jsancio** [comment]
@aeyakovenko @BenWhitehead Should we create a milestone for these issues?

**Comment by vkostyukov** [comment]
I'm happy to chat about that if you want. Do you need multiple content-types? What else do you use besides JSON.

My plan is to roll out something in 0.11 that would make it easier, but I'm not sure on the 0.11 timeline yet.

**Comment by BenWhitehead** [comment]
@vkostyukov We need to support the complex format allowed in the `Accept` header where a client can specify multiple types with Quality values and the server is able to pick the more appropriate response based on this information. We also need for the type to be a complex type rather than string. The order of params in a media type are not significant when evaluating compatibility.

We have a case class [`MediaType`](https://github.com/dcos/cosmos/blob/master/cosmos-server/src/main/scala/com/mesosphere/cosmos/http/MediaType.scala#L21) that represents the format of a media type and [`MediaTypeOps`](https://github.com/dcos/cosmos/blob/master/cosmos-server/src/main/scala/com/mesosphere/cosmos/http/MediaTypeOps.scala#L18) that represent the operations we perform on `MediaType`s. There is a fairly comprehensive [test suite](https://github.com/dcos/cosmos/tree/master/cosmos-server/src/test/scala/com/mesosphere/cosmos/http) that outlines several of the scenarios supported currently by us

Not sure if you're interested, but  PR #484 is where I implemented the content negotiation a few weeks ago.

**Comment by vkostyukov** [comment]
Thanks @BenWhitehead!

That's interesting! So you go to `Endpoint[Response]` already? I assume it's not easy to do content-type-negotiation with `Endpoint[Foo]`?

**Comment by BenWhitehead** [comment]
We've got some custom plumbing in place to essentially map paths to business Response objects (Not http response). One possible thing of note, we're doing more RPC style where everything things is an object sent via POST with a response. Nothing rest related.

All of the header rules are encapsulated by our [`RequestValidators`](https://github.com/dcos/cosmos/blob/master/cosmos-server/src/main/scala/com/mesosphere/cosmos/handler/RequestValidators.scala#L35) Which ensure we have circe encoder/decoder and corresponding media types for each of the endpoints.

**Comment by jsancio** [comment]
Migrated to https://dcosjira.atlassian.net/browse/DCOS-423
