### ISSUE TITLE
Optional command-line flag providing S3 bucket URI

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#468]
To enable the storage of uploaded packages in DC/OS, Cosmos needs the URI of the S3 bucket where they should be written. Update Cosmos so that it behaves as follows:

- The bucket URI is the content of a ZooKeeper node at a well-known path `p`; if the node does not exist, then it is the argument of a specific command-line flag; if the flag was not specified, then the URI is not defined.
- If the URI is defined, it must be stored in the ZooKeeper node at path `p`. The node should be created if needed.
- If the URI is not defined, then the package upload feature is disabled: Cosmos must respond with an error if a request attempts to use the feature.

**Comment by BenWhitehead** [comment]
This shouldn't be a command line flag, it should an application level configuration that the user can provide through the API.

Asking users to manage command flags will most likely break when dcos update time rolls around since the flags are set in files that are managed by dcos itself and not the applications.

**Comment by cruhland** [comment]
@BenWhitehead good point. If the config is provided via an API call, we need to figure out how to invoke that in the CloudFormation templates for CCM clusters. We want the S3 storage to "just work" on CCM clusters without manual configuration by users.

**Comment by jsancio** [comment]
Migrated.
