### ISSUE TITLE
Update `CosmosRepository` to avoid redundant repo downloads

### ISSUE THREAD

**Issue by cruhland** [dcos/cosmos#470]
First, determine whether we should use `If-Modified-Since` or `ETag` for deciding if repo content has changed. This should take into account the approach that will make the most sense for the `/package/storage/repo` endpoint.

Then, modify `CosmosRepository.synchronizedUpdate()` to use the selected strategy for repos that support it.

See #162 for details about possible implementations.

**Comment by jsancio** [comment]
We should optimize our universe update call so that we only receive the latest zip if the resource has been updated. Here are some possible solutions:

- We can use HTTP's if-modified-since header when creating the GET request to download the zip file

- We can remember the Etag and send an if-none-match header when creating the GET request to download the ZIP file

**Comment by jsancio** [comment]
Migrated.
