### ISSUE TITLE
Mechanism for notifying storage change

### ISSUE THREAD

**Issue by jsancio** [dcos/cosmos#478]
We need to implement a mechanism for notifying all the Cosmos that the local repository has change. We are going to use this to determine if Cosmos should perform a read against the S3 storage.

```
trait DistributedVar {
  def get: Future[String]
  def put(value: String): Future[Unit]
}
```

Curator recipe: https://curator.apache.org/curator-recipes/node-cache.html

**Comment by larioj** [comment]
We have decided to make distributed var generic.

We are changing the interface to be:
```scala
trait DistributedVar[T] {
  def get: Future[T]
  def put(value: T): Future[T]
}
```

In order to implement distributed var we need some infrastructure
1. We need a way to decode and encode the type T that is stored
2. We need to keep any state that we externalize versioned
3. We need a ZookeeperDriver that will provide us with zookeeper CRUD operations

All of the above infrastructure exists in Cosmos already, but it is tied to ZkRepositoryList. This suggests that the first steps towards the implementation of distributed var is to refactor the functionality so that it can be used to satisfy 1, 2 and 3 above.

This also suggests a decomposition into 3 PRs.
1. Refactor MediaTypedDecoder to support the need to associate just an Circe.Decoder and a MediaType. Currently it associates a finch.DecodeRequest with a mediaType, which is inconsistent with it's name. See Issue #500 for more info
2. ZkRepositoryList keeps elements versioned using an envelope. This functionality should be factored out and generalized to accommodate types beyond the repo list. See Issue #501 for more info.
3. ZkRepositoryList has some zookeeper operations that can be factored. These operation can be leveraged in Distributed var. See issue #502.

After the above refactoring has been completed, implementation of distributed var can begin.

Note that the PRs outlined above will happen against master while the distributed var PR will occur against distributed-publish. The reason for the master PRs is because PR 1 2 and 3 are changing existing components. While the distributed var PR will be adding new functionality. Making the PRs to master will make it easier to merge down the line.

**Comment by jsancio** [comment]
Migrated.
